
# -----------------------------------------------------------
# 1. CONFIG SERVER
# -----------------------------------------------------------

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: config-service
  labels:
    name: config-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: config-service
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: shridhar71/spring-app:config-server
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: config-service
  labels:
    app: config-server
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
    - name: http
      port: 8888
      targetPort: 8888
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: config-server-monitor
  namespace: config-service
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: config-server        # ← matches your Service label
  endpoints:
    - port: http                # ← matches the named port on the Service
      path: /actuator/prometheus
      interval: 30s
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-email-secret
  namespace: monitoring
type: Opaque
stringData:
  smtp_user: alerts@company.com
  smtp_password: EMAIL_PASSWORD
